name: BedWars
version: 3.0
api: [3.0.0]
main: GPlug\BedWars-PM
author: 
 - Bluplayz
 - MrKiAN
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [BW-PM]
    Start:
        description: Bedwars Forcestart Command
